close all;clear all;clc;
beta=0:1/10000:1;
logZ=zeros(4,1);
LP=zeros(4,1);
load test;
load h10;
logZ(1)=AIS(parameter_W,parameter_b,parameter_a,beta);
LP(1)=calculate_logprob(parameter_W,parameter_b,parameter_a,logZ(1),testbatchdata);
load h20;
logZ(2)=AIS(parameter_W,parameter_b,parameter_a,beta);
LP(2)=calculate_logprob(parameter_W,parameter_b,parameter_a,logZ(2),testbatchdata);
load h100;
logZ(3)=AIS(parameter_W,parameter_b,parameter_a,beta);
LP(3)=calculate_logprob(parameter_W,parameter_b,parameter_a,logZ(3),testbatchdata);
load h500;
logZ(4)=AIS(parameter_W,parameter_b,parameter_a,beta);
LP(4)=calculate_logprob(parameter_W,parameter_b,parameter_a,logZ(4),testbatchdata);
output=[logZ;LP];
save('z.mat','output');
